version: '3'

services:
  myapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=HOTEL
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: HOTEL
    ports:
      - "3306:3306"